# Velux Integration services

reboot_gateway:

set_cover_position:
  target:
    entity:
      domain: cover
  fields:
    position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    velocity:
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

open_cover:
  target:
    entity:
      domain: cover
  fields:
    velocity:
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

close_cover:
  target:
    entity:
      domain: cover
  fields:
    velocity:
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
